import crypto from "node:crypto";
import fs from "node:fs";
import spec from "../src/sy.converter.spec.json" with { type: "json" };
import { createConverter } from "../src/converter-engine.mjs";

const source = fs.readFileSync(new URL("../src/SeferYetzirah.tsx", import.meta.url));
const sourceText = source.toString("utf8");
const sourceHash = crypto.createHash("sha256").update(source).digest("hex");
const corpus = createConverter(spec)(sourceText);
const sourceMap = JSON.parse(fs.readFileSync(new URL("../src/sy.source-map.json", import.meta.url), "utf8"));
const readingUnits = JSON.parse(fs.readFileSync(new URL("../src/sy.reading-units.json", import.meta.url), "utf8"));
const readingHierarchy = JSON.parse(fs.readFileSync(new URL("../src/sy.reading-hierarchy.json", import.meta.url), "utf8"));
const textProjection = JSON.parse(fs.readFileSync(new URL("../src/sy.text-projection.json", import.meta.url), "utf8"));
const textContext = JSON.parse(fs.readFileSync(new URL("../src/sy.text-context.json", import.meta.url), "utf8"));
const corpusScope = JSON.parse(fs.readFileSync(new URL("../src/sy.corpus-scope.json", import.meta.url), "utf8"));
const corpusText = JSON.parse(fs.readFileSync(new URL("../src/sy.corpus-text.json", import.meta.url), "utf8"));
const wordContract = JSON.parse(fs.readFileSync(new URL("../src/sy.word-contract.json", import.meta.url), "utf8"));
const lexicalAmbiguities = JSON.parse(fs.readFileSync(new URL("../src/sy.lexical-ambiguities.json", import.meta.url), "utf8"));
const hyphenUnits = JSON.parse(fs.readFileSync(new URL("../src/sy.hyphen-units.json", import.meta.url), "utf8"));
const internalQuoteUnits = JSON.parse(fs.readFileSync(new URL("../src/sy.internal-quote-units.json", import.meta.url), "utf8"));
const sealedWordUnits = JSON.parse(fs.readFileSync(new URL("../src/sy.sealed-word-units.json", import.meta.url), "utf8"));
const lexicalCoverage = JSON.parse(fs.readFileSync(new URL("../src/sy.lexical-coverage.json", import.meta.url), "utf8"));
const hebrewGraphemes = JSON.parse(fs.readFileSync(new URL("../src/sy.hebrew-graphemes.json", import.meta.url), "utf8"));
const orthographicStream = JSON.parse(fs.readFileSync(new URL("../src/sy.orthographic-stream.json", import.meta.url), "utf8"));
const wordCandidateViews = JSON.parse(fs.readFileSync(new URL("../src/sy.word-candidate-views.json", import.meta.url), "utf8"));
const trailingApostropheCases = JSON.parse(fs.readFileSync(new URL("../src/sy.trailing-apostrophe-cases.json", import.meta.url), "utf8"));
const editorialCandidateInventory = JSON.parse(fs.readFileSync(new URL("../src/sy.editorial-candidate-inventory.json", import.meta.url), "utf8"));
const failures = [];
const requireInvariant = (condition, name) => {
  if (!condition) failures.push(name);
};

requireInvariant(sourceHash === spec.source.local_edition.sha256, "sealed_source_hash");
requireInvariant(!sourceText.includes('וברמ"ב'), "commentator_attribution_1_removed");
requireInvariant(!sourceText.includes('וע"ז קַאי פִּי\' הרמ"ב:'), "commentator_attribution_2_removed");
requireInvariant(sourceText.includes('בִּדְפוּס מַנְטוֹבָה (שכ"ב) הֵגַי\' כמ"ש בְּאוֹצַר ה\''), "attribution_1_interpretive_text_retained");
requireInvariant(sourceText.includes('וסצר"ש בֵּין הַשִּׁנַּיִם וְלָשׁוֹן שְׁכוּבָה וּשְׁטוּתָהּ.'), "attribution_2_interpretive_text_retained");
requireInvariant(sourceMap.source.sha256 === sourceHash, "source_map_source_hash");
requireInvariant(sourceMap.status === "sealed", "source_map_sealed");
requireInvariant(sourceMap.semantic_status === "none", "source_map_has_no_semantics");
requireInvariant(sourceMap.proof.every_root_code_unit_covered_exactly_once, "source_map_unique_coverage");
requireInvariant(sourceMap.proof.exact_root_round_trip, "source_map_round_trip");
requireInvariant(sourceMap.proof.deterministic_output, "source_map_deterministic");
requireInvariant(readingUnits.source.sha256 === sourceHash, "reading_units_source_hash");
requireInvariant(readingUnits.status === "sealed", "reading_units_sealed");
requireInvariant(readingUnits.semantic_status === "none", "reading_units_have_no_semantics");
requireInvariant(readingUnits.proof.every_source_map_node_assigned_exactly_once, "reading_units_unique_coverage");
requireInvariant(readingUnits.proof.every_br_used_exactly_once_as_a_boundary, "reading_units_all_br_boundaries");
requireInvariant(readingUnits.proof.exact_root_round_trip, "reading_units_round_trip");
requireInvariant(readingUnits.proof.deterministic_output, "reading_units_deterministic");
requireInvariant(readingUnits.proof.stable_ordinal_ids, "reading_units_stable_ids");
requireInvariant(readingHierarchy.source.sha256 === sourceHash, "reading_hierarchy_source_hash");
requireInvariant(readingHierarchy.status === "sealed", "reading_hierarchy_sealed");
requireInvariant(readingHierarchy.semantic_status === "none", "reading_hierarchy_has_no_semantics");
requireInvariant(readingHierarchy.proof.every_source_map_node_processed_exactly_once, "reading_hierarchy_node_coverage");
requireInvariant(readingHierarchy.proof.every_tracked_element_closed, "reading_hierarchy_elements_closed");
requireInvariant(readingHierarchy.proof.every_reading_unit_assigned_exactly_once, "reading_hierarchy_unit_coverage");
requireInvariant(readingHierarchy.proof.every_reference_resolves, "reading_hierarchy_references");
requireInvariant(readingHierarchy.proof.deterministic_output, "reading_hierarchy_deterministic");
requireInvariant(textProjection.source.sha256 === sourceHash, "text_projection_source_hash");
requireInvariant(textProjection.status === "sealed", "text_projection_sealed");
requireInvariant(textProjection.semantic_status === "none", "text_projection_has_no_semantics");
requireInvariant(textProjection.proof.every_text_node_projected_exactly_once, "text_projection_node_coverage");
requireInvariant(textProjection.proof.every_fragment_matches_source_range, "text_projection_source_ranges");
requireInvariant(textProjection.proof.exact_text_node_stream_round_trip, "text_projection_round_trip");
requireInvariant(textProjection.proof.every_reading_unit_projected_exactly_once, "text_projection_unit_coverage");
requireInvariant(textProjection.proof.deterministic_output, "text_projection_deterministic");
requireInvariant(textContext.source.sha256 === sourceHash, "text_context_source_hash");
requireInvariant(textContext.status === "sealed", "text_context_sealed");
requireInvariant(textContext.semantic_status === "none", "text_context_has_no_semantics");
requireInvariant(textContext.corpus_scope_status === "undecided", "text_context_scope_undecided");
requireInvariant(textContext.proof.every_text_node_mapped_exactly_once, "text_context_node_coverage");
requireInvariant(textContext.proof.every_jsx_element_closed, "text_context_elements_closed");
requireInvariant(textContext.proof.every_ancestor_reference_resolves, "text_context_ancestors");
requireInvariant(textContext.proof.every_projection_reference_resolves, "text_context_projection_refs");
requireInvariant(textContext.proof.every_corpus_decision_remains_unset, "text_context_no_scope_invention");
requireInvariant(textContext.proof.deterministic_output, "text_context_deterministic");
requireInvariant(corpusScope.source.sha256 === sourceHash, "corpus_scope_source_hash");
requireInvariant(corpusScope.status === "sealed", "corpus_scope_sealed");
requireInvariant(corpusScope.proof.every_text_node_decided_exactly_once, "corpus_scope_node_coverage");
requireInvariant(corpusScope.proof.every_decision_exclusive, "corpus_scope_exclusive");
requireInvariant(corpusScope.proof.no_unresolved_text_nodes, "corpus_scope_resolved");
requireInvariant(corpusScope.proof.counts_match_user_decision, "corpus_scope_user_counts");
requireInvariant(corpusScope.proof.included_source_order_preserved, "corpus_scope_source_order");
requireInvariant(corpusScope.proof.total_included_count === 361, "corpus_scope_included_count");
requireInvariant(corpusScope.proof.deterministic_output, "corpus_scope_deterministic");
requireInvariant(corpusText.source.sha256 === sourceHash, "corpus_text_source_hash");
requireInvariant(corpusText.status === "sealed", "corpus_text_sealed");
requireInvariant(corpusText.proof.every_included_node_present_exactly_once, "corpus_text_included_coverage");
requireInvariant(corpusText.proof.no_excluded_node_present, "corpus_text_no_excluded_nodes");
requireInvariant(corpusText.proof.every_fragment_matches_source_range, "corpus_text_source_ranges");
requireInvariant(corpusText.proof.included_source_order_preserved, "corpus_text_source_order");
requireInvariant(corpusText.proof.every_fragment_assigned_to_one_reading_unit, "corpus_text_unit_assignment");
requireInvariant(corpusText.proof.exact_included_text_stream_round_trip, "corpus_text_round_trip");
requireInvariant(corpusText.proof.counts_match_sealed_scope, "corpus_text_scope_counts");
requireInvariant(corpusText.proof.deterministic_output, "corpus_text_deterministic");
requireInvariant(wordContract.status === "sealed_partial", "word_contract_sealed_partial");
requireInvariant(wordContract.rules.hyphen_connectors.status === "sealed", "word_contract_hyphens_sealed");
requireInvariant(wordContract.rules.initialisms.status === "sealed", "word_contract_initialisms_sealed");
requireInvariant(wordContract.rules.attached_prefixes.surface_representation === "required", "word_contract_prefix_surface_required");
requireInvariant(wordContract.rules.attached_prefixes.decomposed_representation === "required", "word_contract_prefix_decomposition_required");
requireInvariant(wordContract.rules.attached_prefixes.segmentation_rules === "unknown", "word_contract_prefix_rules_unknown");
requireInvariant(wordContract.rules.numbers_and_verse_markers.status === "unknown", "word_contract_numbers_unknown");
requireInvariant(wordContract.rules.punctuation.entity_role === "unknown", "word_contract_punctuation_unknown");
requireInvariant(wordContract.rules.niqqud.unpointed_derivative === "unknown", "word_contract_unpointed_unknown");
requireInvariant(lexicalAmbiguities.source.sha256 === sourceHash, "lexical_inventory_source_hash");
requireInvariant(lexicalAmbiguities.status === "sealed_observation", "lexical_inventory_sealed");
requireInvariant(lexicalAmbiguities.semantic_status === "no_words_or_tokens_defined", "lexical_inventory_no_tokens");
requireInvariant(lexicalAmbiguities.proof.every_corpus_fragment_scanned_exactly_once, "lexical_inventory_fragment_coverage");
requireInvariant(lexicalAmbiguities.proof.every_corpus_code_unit_classified_exactly_once, "lexical_inventory_code_unit_coverage");
requireInvariant(lexicalAmbiguities.proof.every_recorded_character_matches_source_range, "lexical_inventory_source_ranges");
requireInvariant(lexicalAmbiguities.proof.exact_corpus_stream_round_trip, "lexical_inventory_round_trip");
requireInvariant(lexicalAmbiguities.proof.all_contract_open_decisions_remain_unknown, "lexical_inventory_unknowns_preserved");
requireInvariant(lexicalAmbiguities.proof.no_lexical_units_emitted, "lexical_inventory_no_lexical_units");
requireInvariant(lexicalAmbiguities.proof.deterministic_output, "lexical_inventory_deterministic");
requireInvariant(hyphenUnits.source.sha256 === sourceHash, "hyphen_units_source_hash");
requireInvariant(hyphenUnits.status === "sealed", "hyphen_units_sealed");
requireInvariant(hyphenUnits.proof.exactly_eight_hyphen_units, "hyphen_units_exact_count");
requireInvariant(hyphenUnits.proof.every_recorded_hyphen_assigned_exactly_once, "hyphen_units_connector_coverage");
requireInvariant(hyphenUnits.proof.every_unit_matches_exact_source_range, "hyphen_units_source_ranges");
requireInvariant(hyphenUnits.proof.every_unit_has_content_on_both_sides, "hyphen_units_both_sides");
requireInvariant(hyphenUnits.proof.no_unit_contains_whitespace, "hyphen_units_no_whitespace");
requireInvariant(hyphenUnits.proof.adjacent_punctuation_excluded_and_preserved, "hyphen_units_punctuation_preserved");
requireInvariant(hyphenUnits.proof.exact_corpus_round_trip_after_overlay_removal, "hyphen_units_round_trip");
requireInvariant(hyphenUnits.proof.no_non_hyphen_words_emitted, "hyphen_units_scope_limit");
requireInvariant(hyphenUnits.proof.deterministic_output, "hyphen_units_deterministic");
requireInvariant(internalQuoteUnits.source.sha256 === sourceHash, "internal_quote_units_source_hash");
requireInvariant(internalQuoteUnits.status === "sealed", "internal_quote_units_sealed");
requireInvariant(internalQuoteUnits.proof.every_quote_mark_classified_exactly_once, "internal_quote_all_marks_classified");
requireInvariant(internalQuoteUnits.proof.every_internal_quote_assigned_to_one_word, "internal_quote_unit_assignment");
requireInvariant(internalQuoteUnits.proof.every_non_internal_quote_remains_unknown, "internal_quote_unknowns_preserved");
requireInvariant(internalQuoteUnits.proof.every_unit_matches_exact_source_range, "internal_quote_source_ranges");
requireInvariant(internalQuoteUnits.proof.every_unit_has_hebrew_content_on_both_sides, "internal_quote_both_sides");
requireInvariant(internalQuoteUnits.proof.adjacent_punctuation_excluded_and_preserved, "internal_quote_punctuation_preserved");
requireInvariant(internalQuoteUnits.proof.exact_corpus_round_trip_after_overlay_removal, "internal_quote_round_trip");
requireInvariant(internalQuoteUnits.proof.no_non_internal_quote_words_emitted, "internal_quote_scope_limit");
requireInvariant(internalQuoteUnits.proof.no_linguistic_subtype_inferred, "internal_quote_no_subtype_inference");
requireInvariant(internalQuoteUnits.proof.deterministic_output, "internal_quote_deterministic");
requireInvariant(sealedWordUnits.source.sha256 === sourceHash, "sealed_words_source_hash");
requireInvariant(sealedWordUnits.status === "sealed", "sealed_words_sealed");
requireInvariant(sealedWordUnits.proof.exactly_ninety_one_signed_occurrences, "sealed_words_exact_count");
requireInvariant(sealedWordUnits.proof.every_input_occurrence_included_exactly_once, "sealed_words_input_coverage");
requireInvariant(sealedWordUnits.proof.no_occurrence_ranges_overlap, "sealed_words_no_overlap");
requireInvariant(sealedWordUnits.proof.source_order_preserved, "sealed_words_source_order");
requireInvariant(sealedWordUnits.proof.every_occurrence_matches_exact_source_range, "sealed_words_source_ranges");
requireInvariant(sealedWordUnits.proof.every_occurrence_identifies_its_recognition_rule, "sealed_words_rules_present");
requireInvariant(sealedWordUnits.proof.exact_pointed_frequency_counts_cover_every_occurrence, "sealed_words_frequency_coverage");
requireInvariant(sealedWordUnits.proof.exact_corpus_round_trip_after_overlay_removal, "sealed_words_round_trip");
requireInvariant(sealedWordUnits.proof.no_new_word_occurrences_emitted, "sealed_words_no_new_words");
requireInvariant(sealedWordUnits.proof.no_unpointed_identity_emitted, "sealed_words_no_unpointed_identity");
requireInvariant(sealedWordUnits.proof.no_prefix_analysis_or_semantic_interpretation_emitted, "sealed_words_no_semantics");
requireInvariant(sealedWordUnits.proof.deterministic_output, "sealed_words_deterministic");
requireInvariant(lexicalCoverage.source.sha256 === sourceHash, "lexical_coverage_source_hash");
requireInvariant(lexicalCoverage.status === "sealed", "lexical_coverage_sealed");
requireInvariant(lexicalCoverage.semantic_status === "coverage_only", "lexical_coverage_no_semantics");
requireInvariant(lexicalCoverage.proof.every_corpus_code_unit_covered_exactly_once, "lexical_coverage_exact_coverage");
requireInvariant(lexicalCoverage.proof.exact_corpus_stream_round_trip, "lexical_coverage_round_trip");
requireInvariant(lexicalCoverage.proof.every_segment_matches_exact_source_range, "lexical_coverage_source_ranges");
requireInvariant(lexicalCoverage.proof.segments_preserve_source_order_without_fragment_gaps, "lexical_coverage_order_and_gaps");
requireInvariant(lexicalCoverage.proof.exactly_four_allowed_categories, "lexical_coverage_categories");
requireInvariant(lexicalCoverage.proof.all_ninety_one_sealed_words_preserved_exactly_once, "lexical_coverage_words_preserved");
requireInvariant(lexicalCoverage.proof.no_new_words_or_candidates_emitted, "lexical_coverage_no_new_words");
requireInvariant(lexicalCoverage.proof.all_nonword_segments_uninterpreted, "lexical_coverage_nonwords_uninterpreted");
requireInvariant(lexicalCoverage.proof.category_counts_cover_corpus, "lexical_coverage_counts");
requireInvariant(lexicalCoverage.proof.deterministic_output, "lexical_coverage_deterministic");
requireInvariant(hebrewGraphemes.source.sha256 === sourceHash, "hebrew_graphemes_source_hash");
requireInvariant(hebrewGraphemes.status === "sealed", "hebrew_graphemes_sealed");
requireInvariant(hebrewGraphemes.semantic_status === "orthographic_atoms_only", "hebrew_graphemes_no_semantics");
requireInvariant(hebrewGraphemes.proof.every_hebrew_letter_emitted_exactly_once, "hebrew_graphemes_letter_coverage");
requireInvariant(hebrewGraphemes.proof.every_combining_mark_attached_exactly_once, "hebrew_graphemes_mark_coverage");
requireInvariant(hebrewGraphemes.proof.every_hebrew_letter_and_mark_code_unit_covered_exactly_once, "hebrew_graphemes_code_unit_coverage");
requireInvariant(hebrewGraphemes.proof.every_grapheme_has_one_hebrew_base, "hebrew_graphemes_one_base");
requireInvariant(hebrewGraphemes.proof.every_suffix_code_point_is_a_combining_mark, "hebrew_graphemes_mark_suffix");
requireInvariant(hebrewGraphemes.proof.every_grapheme_matches_exact_source_range, "hebrew_graphemes_source_ranges");
requireInvariant(hebrewGraphemes.proof.graphemes_are_nonoverlapping_and_in_source_order, "hebrew_graphemes_order");
requireInvariant(hebrewGraphemes.proof.sealed_word_association_is_all_or_none, "hebrew_graphemes_word_association");
requireInvariant(hebrewGraphemes.proof.exact_corpus_round_trip_after_overlay_removal, "hebrew_graphemes_round_trip");
requireInvariant(hebrewGraphemes.proof.no_words_or_unpointed_word_forms_emitted, "hebrew_graphemes_no_words");
requireInvariant(hebrewGraphemes.proof.no_semantic_interpretation_emitted, "hebrew_graphemes_no_interpretation");
requireInvariant(hebrewGraphemes.proof.deterministic_output, "hebrew_graphemes_deterministic");
requireInvariant(orthographicStream.source.sha256 === sourceHash, "orthographic_stream_source_hash");
requireInvariant(orthographicStream.status === "sealed", "orthographic_stream_sealed");
requireInvariant(orthographicStream.semantic_status === "ordered_orthographic_composition_only", "orthographic_stream_no_semantics");
requireInvariant(orthographicStream.proof.every_corpus_code_unit_represented_exactly_once, "orthographic_stream_exact_coverage");
requireInvariant(orthographicStream.proof.exact_corpus_stream_round_trip, "orthographic_stream_round_trip");
requireInvariant(orthographicStream.proof.every_atom_matches_exact_source_range, "orthographic_stream_source_ranges");
requireInvariant(orthographicStream.proof.atom_stream_is_gap_free_and_nonoverlapping_per_fragment, "orthographic_stream_no_gaps_or_overlap");
requireInvariant(orthographicStream.proof.all_ninety_one_sealed_words_are_single_atoms, "orthographic_stream_words_atomic");
requireInvariant(orthographicStream.proof.every_grapheme_represented_exactly_once_as_atom_or_word_child, "orthographic_stream_grapheme_coverage");
requireInvariant(orthographicStream.proof.no_word_child_grapheme_is_a_top_level_atom, "orthographic_stream_no_child_duplication");
requireInvariant(orthographicStream.proof.every_word_child_is_fully_contained, "orthographic_stream_children_contained");
requireInvariant(orthographicStream.proof.only_five_declared_atom_kinds, "orthographic_stream_kinds");
requireInvariant(orthographicStream.proof.no_words_candidates_normalization_or_interpretation_added, "orthographic_stream_no_new_semantics");
requireInvariant(orthographicStream.proof.deterministic_output, "orthographic_stream_deterministic");
requireInvariant(wordCandidateViews.source.sha256 === sourceHash, "word_candidate_views_source_hash");
requireInvariant(wordCandidateViews.status === "sealed_derivation", "word_candidate_views_sealed");
requireInvariant(wordCandidateViews.semantic_status === "candidates_only_no_new_words", "word_candidate_views_no_words");
requireInvariant(wordCandidateViews.proof.exactly_two_parallel_views, "word_candidate_views_exactly_two");
requireInvariant(wordCandidateViews.proof.neither_view_is_preferred, "word_candidate_views_no_preference");
requireInvariant(wordCandidateViews.proof.every_view_covers_every_atom_exactly_once, "word_candidate_views_atom_coverage");
requireInvariant(wordCandidateViews.proof.every_view_round_trips_exact_corpus, "word_candidate_views_round_trip");
requireInvariant(wordCandidateViews.proof.every_view_segment_matches_source, "word_candidate_views_source_ranges");
requireInvariant(wordCandidateViews.proof.no_view_segment_crosses_a_corpus_fragment, "word_candidate_views_fragment_boundaries");
requireInvariant(wordCandidateViews.proof.all_sealed_words_preserved_in_both_views, "word_candidate_views_sealed_words");
requireInvariant(wordCandidateViews.proof.every_candidate_contains_a_grapheme, "word_candidate_views_graphemes");
requireInvariant(wordCandidateViews.proof.no_candidate_is_promoted_to_word, "word_candidate_views_candidate_status");
requireInvariant(wordCandidateViews.proof.punctuation_role_remains_unknown, "word_candidate_views_punctuation_unknown");
requireInvariant(wordCandidateViews.proof.every_difference_case_resolves_in_both_views, "word_candidate_views_difference_references");
requireInvariant(wordCandidateViews.proof.no_normalization_prefix_analysis_or_interpretation, "word_candidate_views_no_semantics");
requireInvariant(wordCandidateViews.proof.deterministic_output, "word_candidate_views_deterministic");
requireInvariant(trailingApostropheCases.source.sha256 === sourceHash, "trailing_apostrophes_source_hash");
requireInvariant(trailingApostropheCases.status === "sealed_structural_classification", "trailing_apostrophes_sealed");
requireInvariant(trailingApostropheCases.semantic_status === "all_roles_unknown", "trailing_apostrophes_roles_unknown");
requireInvariant(trailingApostropheCases.proof.all_thirty_two_unknown_quotes_accounted_exactly_once, "trailing_apostrophes_exact_coverage");
requireInvariant(trailingApostropheCases.proof.every_case_is_a_trailing_ascii_apostrophe, "trailing_apostrophes_ascii_source");
requireInvariant(trailingApostropheCases.proof.every_case_has_an_immediately_adjacent_hebrew_sequence, "trailing_apostrophes_adjacency");
requireInvariant(trailingApostropheCases.proof.exactly_thirty_single_letter_and_two_multi_letter_shapes, "trailing_apostrophes_shapes");
requireInvariant(trailingApostropheCases.proof.every_case_grapheme_membership_matches_base_letters, "trailing_apostrophes_graphemes");
requireInvariant(trailingApostropheCases.proof.every_case_matches_exact_source_range, "trailing_apostrophes_source_ranges");
requireInvariant(trailingApostropheCases.proof.cases_are_nonoverlapping_and_in_source_order, "trailing_apostrophes_order");
requireInvariant(trailingApostropheCases.proof.every_case_is_present_in_the_punctuation_difference_inventory, "trailing_apostrophes_candidate_differences");
requireInvariant(trailingApostropheCases.proof.every_word_and_semantic_role_remains_unknown, "trailing_apostrophes_unknown_preserved");
requireInvariant(trailingApostropheCases.proof.exact_corpus_round_trip_after_overlay_removal, "trailing_apostrophes_round_trip");
requireInvariant(trailingApostropheCases.proof.no_word_number_abbreviation_or_punctuation_role_inferred, "trailing_apostrophes_no_inference");
requireInvariant(trailingApostropheCases.proof.deterministic_output, "trailing_apostrophes_deterministic");
requireInvariant(editorialCandidateInventory.source.sha256 === sourceHash, "editorial_candidates_source_hash");
requireInvariant(editorialCandidateInventory.status === "sealed_observation", "editorial_candidates_sealed");
requireInvariant(editorialCandidateInventory.semantic_status === "candidates_only_no_editorial_or_corpus_decision", "editorial_candidates_no_decision");
requireInvariant(editorialCandidateInventory.proof.exactly_seven_small_elements_inventoried, "editorial_candidates_small_elements");
requireInvariant(editorialCandidateInventory.proof.exactly_nine_square_bracket_pairs_inventoried, "editorial_candidates_square_brackets");
requireInvariant(editorialCandidateInventory.proof.exactly_seven_parenthesis_pairs_inventoried, "editorial_candidates_parentheses");
requireInvariant(editorialCandidateInventory.proof.every_candidate_matches_exact_source_range, "editorial_candidates_source_ranges");
requireInvariant(editorialCandidateInventory.proof.every_candidate_has_source_context, "editorial_candidates_context");
requireInvariant(editorialCandidateInventory.proof.every_source_node_reference_resolves, "editorial_candidates_node_references");
requireInvariant(editorialCandidateInventory.proof.every_overlap_reference_is_symmetric, "editorial_candidates_overlaps");
requireInvariant(editorialCandidateInventory.proof.every_corpus_and_editorial_role_remains_unknown, "editorial_candidates_unknown");
requireInvariant(editorialCandidateInventory.proof.no_source_or_corpus_change_performed, "editorial_candidates_no_mutation");
requireInvariant(editorialCandidateInventory.proof.candidate_count === 23, "editorial_candidates_exact_count");
requireInvariant(editorialCandidateInventory.proof.deterministic_output, "editorial_candidates_deterministic");
requireInvariant(corpus.validation.valid, "corpus_validation");
requireInvariant(corpus.input === sourceText, "lossless_source");
requireInvariant(corpus.stats.occurrences === 1673, "occurrence_count");
requireInvariant(corpus.stats.names === 740, "name_count");
requireInvariant(corpus.evidence.names.some((name) => name.normalized === "פליאות"), "name_פליאות");
requireInvariant(corpus.structure.records.every((record) => record.boundary_basis === "authoritative_br"), "authoritative_br");
requireInvariant(corpus.units.every((unit) => unit.boundary_authority === "user_interpretation"), "authoritative_reading_groups");

const term = spec.terminology.find((item) => item.term === "מילים כפולות");
requireInvariant(Boolean(term), "term_double_words_exists");
requireInvariant(term?.definition === null, "term_double_words_not_invented");
requireInvariant(term?.status === "awaiting_user_definition", "term_double_words_waiting");
requireInvariant(term?.execution === "forbidden_until_defined", "term_double_words_not_executable");
requireInvariant(term?.assistant_inferences.every((item) => item.status === "rejected"), "assistant_meanings_rejected");
requireInvariant(spec.repetition.authority === "assistant_inference", "repetition_authority_corrected");

const activeCapabilities = spec.capability_registry.filter((item) => item.status === "active");
for (const capability of activeCapabilities) {
  requireInvariant(Boolean(capability.id), "active_capability_has_id");
}

if (failures.length) {
  console.error(JSON.stringify({ valid: false, failures }, null, 2));
  process.exit(1);
}

console.log(JSON.stringify({
  valid: true,
  version: corpus.version,
  source_sha256: sourceHash,
  occurrences: corpus.stats.occurrences,
  names: corpus.stats.names,
  active_capabilities: activeCapabilities.map((item) => item.id),
  protected_undefined_term: term.term,
}, null, 2));
